In [2]:
import pandas as pd
import duckdb

# Test monthly-sales.csv

In [4]:
monthly_sales = pd.read_csv("./csv/monthly-sales.csv")
monthly_sales

,month,SUPPLIER,LICENSEE,PART,qty,month_amt,ytd_amt
0,2023-03,nippon-metal,ninja-roofing,glass-clip,109,128600,128600
1,2023-03,nippon-metal,ninja-roofing,glass-decoration,114,86100,86100
2,2023-03,nippon-metal,ninja-roofing,gold-clip,156,89500,89500
3,2023-03,nippon-metal,ninja-roofing,gold-decoration,165,64400,64400
4,2023-03,nippon-metal,ninja-roofing,roof-polish,57,11100,11100
...,...,...,...,...,...,...,...
872,2026-01,nippon-metal,rice-roofers,tin-decoration,144,16300,16300
873,2026-01,us-steel,ranger-roofing,glass-clip,142,178100,178100
874,2026-01,us-steel,ranger-roofing,gold-clip,120,75800,75800
875,2026-01,us-steel,ranger-roofing,roof-polish,117,27800,27800
876,2026-01,us-steel,ranger-roofing,tin-clip,219,24600,24600

In [5]:
xf = duckdb.query("""
select * 
from monthly_sales
where 
    month between '2023-03' and '2023-06'
    and
    supplier = 'nippon-metal'
    and 
    licensee = 'ninja-roofing'
    and 
    part = 'glass-clip'
""").df()

xf

     month      SUPPLIER       LICENSEE        PART  qty  month_amt  ytd_amt
0  2023-03  nippon-metal  ninja-roofing  glass-clip  109     128600   128600
1  2023-05  nippon-metal  ninja-roofing  glass-clip  101     103900   232500
2  2023-06  nippon-metal  ninja-roofing  glass-clip  225     231600   464100